language: go
os:
- linux
- osx
go:
- 1.8
- 1.9
script:
- go test
env:
  matrix:
    - secure: rMnBy/E2g9aeDijkpoELVEoRAXzO69bpIOIYCMsCCYCBBE7LmFvsofa/U7gxpcUj5WtTymPGP72hYm1A0XOQa9xT7faZe0cy63kdj2hbi/49p06/SUEnxEFnSPWOGrEGOgfJzeatnvFo/D+MLJb1RIx411LDPJqvHufxSn1BrW8vZuC5gXwm400xaoGP1ZTF8S5BlSWl97jLXz13XeXAE1VocxoruMuKDrA5W+dGoU12RQBgDGKqGoD9eulW8kdqThHR81k4YK5OmmoF7zQyufzx7Z/KaUCp1WAX4MbBGo61rcLJbgjnJaxVsLEGtnjdVReg6KirABv3VsRbMHEd7gSIIconRhXhgwril1MLPWDyBuWX7g1CXrKkP6tPZIXMGcFeRtJwJPsf+GOXIWg/tS8XkWJNKLOvcaqukSgUFOuovGlnAvI5O4MlL/dnjvm/Z4FQkxncnAMrtlNP2acMdNG7BVzflHZyNtU/63PvvSX4/bYesTOZYfbp+NcShm417RK2NnBDzF/qwKg0OVRXyiAdgDRDBPm1q4+VMGThoSw7/FdqzQKKPqVOpZVG44GAO964Si9hyMFpBOpk60ynrSgf91DjesTo7n8mDrXt2pOHvKQuusk97m+s6X6tTIYJuOO/yacTvyWo2NvvWm84NAXYa1tvrctOA/IMo9T8SVo=